[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
arbitrum_mainnet = "https://arb1.arbitrum.io/rpc"

[etherscan]
arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }